name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
      run:  |
        cd frontend
        npm install

    - name: Run tests ğŸ§ª
      run:  |
        cd frontend
        npm run test

    - name: Generate static page
      env:
        REACT_APP_STRIPE_KEY: ${{ secrets.REACT_APP_STRIPE_KEY }}
        REACT_APP_PRODUCT_ID: ${{ secrets.REACT_APP_PRODUCT_ID }}
        REACT_APP_PAYMENT_API_URL: ${{ secrets.REACT_APP_PAYMENT_API_URL }}
      run:  |
        cd frontend
        npm run build

    - name: deploy to Github Page
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ./frontend/build
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: error
