name: Deploy

on:
  # â˜…â˜…â˜…Github Actionsã‚’èµ·å‹•ã™ã‚‹ãƒ–ãƒ©ãƒ³ãƒâ˜…â˜…â˜…
  push:
    branches: [ master ]

  # Github Actionsã‚’æ‰‹å‹•ã§èµ·å‹•ã§ãã‚‹ã‚ˆã†ã«ã™ã‚‹ã€‚
  workflow_dispatch:

# ã“ã‚Œã‚’æŒ‡å®šã—ã¦ã„ã‚‹ã¨ã€é‡è¤‡ã—ã¦ActionsãŒèµ°ã£ãŸæ™‚ã«å‰ã®ã‚’ã‚­ãƒ£ãƒ³ã‚»ãƒ«ã—ã¦ãã‚Œã‚‹
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
      run:  |
        cd frontend
        npm install

    - name: Run tests ğŸ§ª
      run:  |
        cd frontend
        npm run test

    - name: Generate static page
      env:
        REACT_APP_STRIPE_KEY: ${{ secrets.REACT_APP_STRIPE_KEY }}
        REACT_APP_PRODUCT_ID: ${{ secrets.REACT_APP_PRODUCT_ID }}
        REACT_APP_PAYMENT_API_URL: ${{ secrets.REACT_APP_PAYMENT_API_URL }}
      run:  |
        cd frontend
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # â˜…â˜…â˜… Deployã™ã‚‹ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒª â˜…â˜…â˜…
        publish_dir: ./frontend/build